"""empty message

Revision ID: 243b864586f8
Revises: 97574b96bf6f
Create Date: 2020-07-12 14:33:58.070684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243b864586f8'
down_revision = '97574b96bf6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trips', 'locations', ['departure_location_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'locations', ['destination_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    # ### end Alembic commands ###
