"""empty message

Revision ID: 5ec2ae6fadcb
Revises: af6f1bf32940
Create Date: 2020-07-12 11:49:39.348107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec2ae6fadcb'
down_revision = 'af6f1bf32940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trips', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    # ### end Alembic commands ###
